name: Image Finder

on:
  workflow_dispatch:
    inputs:
    
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'PD2060F'
      ENV_APP:
        description: 'Environment compress (apt-get)'
        required: true
        default: 'fastjar p7zip-full'
      DOWNLOAD:
        description: 'Firmware_URL (gdown, mediafire-dl, wget)'
        required: true
        default: 'mediafire-dl http://www.mediafire.com/file/ymztakm11lfhssi/Vivo_Y12S_PD2060F_EX_A_1.72.20_LA.UM.9.6.2.r1-02100-89xx-sdm439_Split_QPST.zip'
      UNPACK:
        description: 'Extrac Command'
        required: true
        default: 'unzip -j -o Vivo_Y12S_PD2060F_EX_A_1.72.20_LA.UM.9.6.2.r1-02100-89xx-sdm439_Split_QPST.zip'
      IMG_SELECT:
        description: 'Image Selected (ex. recovery.img)'
        required: true
        default: 'recovery.img'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    # You can use either of the ubuntu-18.04 or ubuntu-20.04 runner
    steps:
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo rm -rf *
        sudo apt-get update >> log.txt
        sudo apt-get install ${{ github.event.inputs.ENV_APP }} -y
        sudo -H pip install wheel
        sudo apt-get install python-setuptools
        sudo -H pip install  gdown
        sudo apt-get install python3-setuptools
        sudo -H pip3 install git+https://github.com/Juvenal-Yescas/mediafire-dl


    - name: Downloading
      run: |
        ${{ github.event.inputs.DOWNLOAD }} 
        
    - name: Extracting
      run: |
        ${{ github.event.inputs.UNPACK }} 
        ls -a

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.event.inputs.UNPACK }}
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Download Url: ${{ github.event.inputs.DOWNLOAD }}
          Extract Command: ${{ github.event.inputs.UNPACK }}
          Image Selected: ${{ github.event.IMG_SELECT }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
