name: Main
on:
  workflow_dispatch:
    inputs:
    
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'PD2060F'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_id }}
          files: |
            *
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
